development:
  server:
    port: "8080"
  database:
    dsn: "dev.db"

testing:
  server:
    port: "8081"
  database:
    dsn: "file::memory:?cache=shared"

production:
  server:
    port: "80"
  database:
    dsn: "prod.db"
